# Tensor
褚则伟 zeweichu@gmail.com

[参考资料 reference](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html)

- 类似于NumPy，但是它可以使用GPU
- 可以用它定义深度学习模型，可以灵活地进行深度学习模型的训练和使用

Tensor类似与NumPy的ndarray，唯一的区别是Tensor可以在GPU上加速运算。

In [1]:
import torch
x = torch.empty(5, 3)
print(x)#未初始化的矩阵，内部数字很大或者很小

tensor([[4.7984e+30, 6.2121e+22, 1.8370e+25],
        [1.4603e-19, 2.7517e+12, 7.5338e+28],
        [3.0313e+32, 6.3828e+28, 1.4603e-19],
        [1.0899e+27, 6.8943e+34, 1.1835e+22],
        [7.0976e+22, 1.8515e+28, 4.1988e+07]])


In [2]:
x = torch.rand(5, 3)
print(x)#随机初始化的5x3矩阵

tensor([[0.5846, 0.8890, 0.4086],
        [0.0781, 0.0037, 0.3882],
        [0.7939, 0.9350, 0.9879],
        [0.1008, 0.1489, 0.5507],
        [0.5740, 0.8620, 0.5222]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)#纯零，长整型矩阵

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)#从已有数据建立tensor

tensor([5.5000, 3.0000])


In [6]:
#建立和x相似的y
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

y = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(y)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.9027, -0.4147,  0.5826],
        [-0.5780, -0.2251, -0.0946],
        [ 0.5957, -0.1121, -0.1514],
        [ 0.5510, -0.6024, -0.2568],
        [ 0.5578,  0.0149, -1.1258]])


<div class="alert alert-info"><h4>注意</h4><p>``torch.Size`` 返回的是一个tuple</p></div>

Resizing: 如果你希望resize/reshape一个tensor，可以使用``torch.view``：

In [18]:
import torch
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [7]:
print(x.size())

torch.Size([5, 3])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

y = torch.randn_like(x, dtype=torch.double)    # override dtype!
print(y)                                      # result has the same size

result = torch.empty(5, 3,dtype=torch.double)#控制相同类型

torch.add(x, y, out=result)
print(result)#add可以把结果内部赋值

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.6645e-01, -2.5956e-01,  2.1666e-02],
        [-2.3782e+00, -1.8990e+00, -2.1766e-01],
        [-2.3248e-01,  1.7069e-01,  1.6158e-01],
        [ 1.0555e-03, -4.6569e-01,  7.3031e-01],
        [-2.9010e-01,  2.0091e+00, -5.2634e-01]], dtype=torch.float64)
tensor([[ 1.1665,  0.7404,  1.0217],
        [-1.3782, -0.8990,  0.7823],
        [ 0.7675,  1.1707,  1.1616],
        [ 1.0011,  0.5343,  1.7303],
        [ 0.7099,  3.0091,  0.4737]], dtype=torch.float64)


In [13]:
# adds x to y
y.add_(x)#原地加法
print(y)

tensor([[ 1.1665,  0.7404,  1.0217],
        [-1.3782, -0.8990,  0.7823],
        [ 0.7675,  1.1707,  1.1616],
        [ 1.0011,  0.5343,  1.7303],
        [ 0.7099,  3.0091,  0.4737]], dtype=torch.float64)


<div class="alert alert-info"><h4>注意</h4><p>任何in-place的运算都会以``_``结尾。
    举例来说：``x.copy_(y)``, ``x.t_()``, 会改变 ``x``。</p></div>

各种类似NumPy的indexing都可以在PyTorch tensor上面使用。

In [14]:
print(x[:, 1])

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())#item可以把value变成python值

tensor([-0.2465])
-0.246506467461586


**更多阅读**


  各种Tensor operations, 包括transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers在
  `<https://pytorch.org/docs/torch>`.

Numpy和Tensor之间的转化
------------

在Torch Tensor和NumPy array之间相互转化非常容易。

Torch Tensor和NumPy array会共享内存，所以改变其中一项也会改变另一项。

把Torch Tensor转变成NumPy Array

In [19]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)#因共享内存，两者都会改变

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
#np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


所有CPU上的Tensor都支持转成numpy或者从numpy转成Tensor。

CUDA Tensors
------------

使用``.to``方法，Tensor可以被移动到别的device上。